Remove use of thread_rng in common
mikelodder7/glass_pumpkin pull request #17
Opened 2022-10-05 10:38 UTC by d86leader

Another patch of bringing this library a bit closer to no_std. Now `rand` crate is used with no_std for library, but with std for tests.

This only touches the functions in "common" module, so does not affect public api.

2022-10-05 16:17 UTC, mikelodder7 commented on Cargo.toml
> +rand = { version = "0.8", default-features = false }
rand_core = "0.6"

2022-10-05 16:18 UTC, mikelodder7 commented on src/common.rs
>  use rand::Rng;
```suggestion
use rand_core::Rng;
```

2022-10-05 16:19 UTC, mikelodder7 requested changes
Thanks for PR. Let's use rand_core since that is a smaller dependency since we only need the trait.

2022-10-06 10:55 UTC, d86leader commented
Good idea. Although doesn't actually matter for dependency size, since num-bigint requires rand anyway.

2022-10-11 16:22 UTC, d86leader commented
@mikelodder7 can you take a look at the new changes? I believe your concerns were addressed by them.

2022-10-11 20:56 UTC, mikelodder7 approved these changes

2022-10-11 20:56 UTC, merged

2022-10-12 08:10 UTC, maurges commented
Thanks!